apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care-app
  labels:
    app: health-care
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-care
  template:
    metadata:
      labels:
        app: health-care
    spec:
      containers:
      - name: health-care-container
        image: ganeshnimmakayala/health-application:v1
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: health-app-svc
  labels:
    app: health-care-svc
spec:
  selector:
    app: health-care

  type: NodePort
  ports:
  - nodePort: 31031 
    port: 8082
    targetPort: 8082
